<a href="https://cognitiveclass.ai"><img src = "https://ibm.box.com/shared/static/9gegpsmnsoo25ikkbl4qzlvlyjbgxs5x.png" width = 400> </a>
<br>
<h1 align=center><font size = 5>IBM Data Science Capstone - Eugene Bible</font></h1>
<h2 align=center>Week 3 - Segmenting and Clustering Neighborhoods in Toronto<h2>

# Introduction

This is the Jupyter Notebook to be used for the Week 3 project in the IBM Data Science Capstone course of the IBM Data Science Professional Certificate program by Coursera.

In this Jupyter notebook, neighborhoods in the city of Toronto will be explored, segmented, and clustered. 
First, the data will be scraped from the Wikipedia page and be wrangled, cleaned, and then read into a pandas dataframe in a structured format. Once structured, the neighborhoods in Toronoto will be explored and clustered.

Author: Eugene Bible

This project link on IBM Watson Studio: https://jp-tok.dataplatform.cloud.ibm.com/analytics/notebooks/v2/007ab5db-57d4-4ac7-b5fd-08ab9d2e0afc/view?projectid=0e052036-fd3e-4893-a04b-46349d1af3d9&context=analytics

This project link on Github: https://github.com/Glitch852/Coursera_Capstone/blob/master/IBM%20Data%20Science%20Capstone%20-%20EB.ipynb

## Table of Contents
<div class="alert alert-block alert-info" style="margin-top: 20px">
<font size = 3>

[1. Scraping the Data and Creating the Dataframe](#1.-Scraping-the-Data-and-Creating-the-Dataframe) <br>
[2. Exploring and Clustering the Groups of Toronto](#2.-Exploring-and-Clustering-the-Groups-of-Toronto)<br>
[3. Clustering the Neighborhoods with K-Means](#3.-Clustering-the-Neighborhoods-with-K\-Means)<br>
[4. Summary and Conclusion](#4.-Summary-and-Conclusion)


</font>
</div>

Import the necessary libraries:

In [59]:
import urllib.request,urllib.parse,urllib.error # Library to parse websites
from bs4 import BeautifulSoup # Library to handle web scraping

import numpy as np # library to handle data in a vectorized manner

import pandas as pd # library for data analsysis
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

#!conda install -c conda-forge geocoder --yes
import geocoder # import geocoder for getting lat/lon

from geopy.geocoders import Nominatim # convert an address into latitude and longitude values

#!conda install -c conda-forge folium=0.5.0 --yes
import folium # map rendering library

import json # library to handle json files

import requests #library to handle requests
from pandas.io.json import json_normalize #transform JSON file into pandas dataframe

# Matplotlib and associated plotting modules
import matplotlib.cm as cm
import matplotlib.colors as colors

# import k-means from clustering stage
from sklearn.cluster import KMeans

print('Libraries imported.')

Libraries imported.


# 1. Scraping the Data and Creating the Dataframe

### Scrape the Wikipedia page to obtain the table of postal codes/boroughs/neighborhoods

Page found at: https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M

In [60]:
# Define the URL of the webpage to scrape
url = 'https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M'
# Get HTML
html = urllib.request.urlopen(url).read()
#print(html)

# Use BeautifulSoup to parse the html
soup = BeautifulSoup(html, 'html.parser')
#print(soup.prettify())

# Parse the table only and pull all rows
table = soup.find('table')
#print(table.prettify())

### Transform the table into a Pandas Dataframe
Requirements:
- The dataframe will consist of three columns: PostalCode, Borough, and Neighborhood
- Only process the cells that have an assigned borough. Ignore cells with a borough that is Not assigned.
- More than one neighborhood can exist in one postal code area. For example, in the table on the Wikipedia page, you will notice that M5A is listed twice and has two neighborhoods: Harbourfront and Regent Park. These two rows will be combined into one row with the neighborhoods separated with a comma as shown in row 11 in the above table.
- If a cell has a borough but a Not assigned neighborhood, then the neighborhood will be the same as the borough. So for the 9th cell in the table on the Wikipedia page, the value of the Borough and the Neighborhood columns will be Queen's Park.
- Clean your Notebook and add Markdown cells to explain your work and any assumptions you are making.
- In the last cell of your notebook, use the .shape method to print the number of rows of your dataframe.

In [61]:
# Scraping the rows of the table
table_rows = table.find_all('tr')

rows = []
for tr in table_rows:
    #print('count = ' + str(count))
    th = tr.find_all('th') # Grab header
    td = tr.find_all('td') # Grab row
    if th:
        row = [th.text.rstrip() for th in th]
        rows.append(row)
    else:
        row = [tr.text.rstrip() for tr in td]
        if row[1] == 'Not assigned': continue # If no borough, don't keep the row
        if row[2] == 'Not assigned': row[2] = row[1] # If neighborhood is not assigned, set it to the Borough
        rows.append(row)  
            
# Assign list of rows to a Pandas DF
nhScraped_df = pd.DataFrame(rows)

# Name the columns after the first row (headers) then drop the header row
nhScraped_df.columns = nhScraped_df.iloc[0]
nhScraped_df = nhScraped_df.drop(nhScraped_df.index[0])
nhScraped_df.head(10)


0  Postcode           Borough     Neighbourhood
1       M3A        North York         Parkwoods
2       M4A        North York  Victoria Village
3       M5A  Downtown Toronto      Harbourfront
4       M6A        North York  Lawrence Heights
5       M6A        North York    Lawrence Manor
6       M7A  Downtown Toronto      Queen's Park
7       M9A      Queen's Park      Queen's Park
8       M1B       Scarborough             Rouge
9       M1B       Scarborough           Malvern
10      M3B        North York   Don Mills North

In [62]:
# Let's check our counts of postal codes, boroughs, and neighborhoods.

print('The dataframe has {} postal codes, {} boroughs, and {} neighborhoods.'.format(
        len(nhScraped_df['Postcode'].unique()),
        len(nhScraped_df['Borough'].unique()),
        len(nhScraped_df['Neighbourhood'].unique())
    )
)

The dataframe has 103 postal codes, 11 boroughs, and 207 neighborhoods.


In [63]:
# Now that we have the 'Not Assigned' entries taken care of, need to combine the rows with the same Postcode but different neighborhoods

# Use groupby to sort the list by Postcode
nhGrouped_df = nhScraped_df.groupby(['Postcode','Borough'])
#print(nhGrouped_df)

# Print to check for proper sorting
for key, item in nhGrouped_df:
    print(nhGrouped_df.get_group(key), "\n\n")

0 Postcode      Borough Neighbourhood
8      M1B  Scarborough         Rouge
9      M1B  Scarborough       Malvern 


0  Postcode      Borough   Neighbourhood
21      M1C  Scarborough  Highland Creek
22      M1C  Scarborough      Rouge Hill
23      M1C  Scarborough      Port Union 


0  Postcode      Borough Neighbourhood
33      M1E  Scarborough     Guildwood
34      M1E  Scarborough   Morningside
35      M1E  Scarborough     West Hill 


0  Postcode      Borough Neighbourhood
39      M1G  Scarborough        Woburn 


0  Postcode      Borough Neighbourhood
43      M1H  Scarborough     Cedarbrae 


0  Postcode      Borough        Neighbourhood
54      M1J  Scarborough  Scarborough Village 


0  Postcode      Borough         Neighbourhood
66      M1K  Scarborough  East Birchmount Park
67      M1K  Scarborough               Ionview
68      M1K  Scarborough          Kennedy Park 


0  Postcode      Borough Neighbourhood
79      M1L  Scarborough      Clairlea
80      M1L  Scarborough   Gold

In [64]:
# Join neighborhoods of the grouped entries (i.e. the groups with the same postcode), separated by commas
nhJoined_df = nhGrouped_df['Neighbourhood'].apply(', '.join)

nhJoined_df = nhJoined_df.reset_index()

nhJoined_df.head(20)

Postcode      Borough                                      Neighbourhood
0       M1B  Scarborough                                     Rouge, Malvern
1       M1C  Scarborough             Highland Creek, Rouge Hill, Port Union
2       M1E  Scarborough                  Guildwood, Morningside, West Hill
3       M1G  Scarborough                                             Woburn
4       M1H  Scarborough                                          Cedarbrae
5       M1J  Scarborough                                Scarborough Village
6       M1K  Scarborough        East Birchmount Park, Ionview, Kennedy Park
7       M1L  Scarborough                    Clairlea, Golden Mile, Oakridge
8       M1M  Scarborough    Cliffcrest, Cliffside, Scarborough Village West
9       M1N  Scarborough                        Birch Cliff, Cliffside West
10      M1P  Scarborough  Dorset Park, Scarborough Town Centre, Wexford ...
11      M1R  Scarborough                                  Maryvale, Wexford
12      M1S  Scarborough                                          Agincourt
13      M1T  Scarborough            Clarks Corners, Sullivan, Tam O'Shanter
14      M1V  Scarborough  Agincourt North, L'Amoreaux East, Milliken, St...
15      M1W  Scarborough                                    L'Amoreaux West
16      M1X  Scarborough                                        Upper Rouge
17      M2H   North York                                  Hillcrest Village
18      M2J   North York                       Fairview, Henry Farm, Oriole
19      M2K   North York                                    Bayview Village

In [65]:
# Check the number of rows in our df, should still have 103 postal codes, meaning 103 rows now.
nhJoined_df.shape

(103, 3)

### Getting latitude and longitude for each neighborhood
Now that we have a dataframe of the postal codes of each neighborhood, borough name, and neighborhood name, to utilize the Foursquare location data, we need to get the latitude and the longitude coordinates of each neighborhood.

In [66]:
## Using Python's built-in geocode NOTE: TOO UNRELIABLE. USED THE GEOSPATIAL_DATA PAGE PROVIDED BY INSTRUCTOR.
#
## initialize your variable to None
#lat_lng_coords = None
#
#address = 'M1J Scarborough Scarborough Village'
#geolocator = Nominatim(user_agent="EB_explores_canada")
#
#while(lat_lng_coords is None):
#    lat_lng_coords = geolocator.geocode(address)
#
#print(lat_lng_coords)
#    
#nlat = lat_lng_coords.latitude
#nlon = lat_lng_coords.longitude
#
#
#print(nlat, nlon)

Note: Package was too unreliable to get all lat/lon values. Used the CSV file that has the geographical coordinates of each postal code: http://cocl.us/Geospatial_data

In [67]:
url = 'http://cocl.us/Geospatial_data'
response = urllib.request.urlopen(url)
latlng_df = pd.read_csv(response)


latlng_df.head()

Postal Code   Latitude  Longitude
0         M1B  43.806686 -79.194353
1         M1C  43.784535 -79.160497
2         M1E  43.763573 -79.188711
3         M1G  43.770992 -79.216917
4         M1H  43.773136 -79.239476

In [68]:
# Change column name so both dataframes have the same column name
latlng_df.rename(columns={'Postal Code': 'Postcode'}, inplace=True)
latlng_df.head()

Postcode   Latitude  Longitude
0      M1B  43.806686 -79.194353
1      M1C  43.784535 -79.160497
2      M1E  43.763573 -79.188711
3      M1G  43.770992 -79.216917
4      M1H  43.773136 -79.239476

In [69]:
# Merge two Dataframes on column 'Postcode'
neighborhoods_df = nhJoined_df.merge(latlng_df, on='Postcode')

neighborhoods_df = neighborhoods_df.rename(columns={'Neighbourhood': 'Neighborhood'}) # Because I'm American. (Sorry.)

neighborhoods_df.head(100)

Postcode           Borough  \
0       M1B       Scarborough   
1       M1C       Scarborough   
2       M1E       Scarborough   
3       M1G       Scarborough   
4       M1H       Scarborough   
5       M1J       Scarborough   
6       M1K       Scarborough   
7       M1L       Scarborough   
8       M1M       Scarborough   
9       M1N       Scarborough   
10      M1P       Scarborough   
11      M1R       Scarborough   
12      M1S       Scarborough   
13      M1T       Scarborough   
14      M1V       Scarborough   
15      M1W       Scarborough   
16      M1X       Scarborough   
17      M2H        North York   
18      M2J        North York   
19      M2K        North York   
20      M2L        North York   
21      M2M        North York   
22      M2N        North York   
23      M2P        North York   
24      M2R        North York   
25      M3A        North York   
26      M3B        North York   
27      M3C        North York   
28      M3H        North York   
29      M3J        North York   
30      M3K        North York   
31      M3L        North York   
32      M3M        North York   
33      M3N        North York   
34      M4A        North York   
35      M4B         East York   
36      M4C         East York   
37      M4E      East Toronto   
38      M4G         East York   
39      M4H         East York   
40      M4J         East York   
41      M4K      East Toronto   
42      M4L      East Toronto   
43      M4M      East Toronto   
44      M4N   Central Toronto   
45      M4P   Central Toronto   
46      M4R   Central Toronto   
47      M4S   Central Toronto   
48      M4T   Central Toronto   
49      M4V   Central Toronto   
50      M4W  Downtown Toronto   
51      M4X  Downtown Toronto   
52      M4Y  Downtown Toronto   
53      M5A  Downtown Toronto   
54      M5B  Downtown Toronto   
55      M5C  Downtown Toronto   
56      M5E  Downtown Toronto   
57      M5G  Downtown Toronto   
58      M5H  Downtown Toronto   
59      M5J  Downtown Toronto   
60      M5K  Downtown Toronto   
61      M5L  Downtown Toronto   
62      M5M        North York   
63      M5N   Central Toronto   
64      M5P   Central Toronto   
65      M5R   Central Toronto   
66      M5S  Downtown Toronto   
67      M5T  Downtown Toronto   
68      M5V  Downtown Toronto   
69      M5W  Downtown Toronto   
70      M5X  Downtown Toronto   
71      M6A        North York   
72      M6B        North York   
73      M6C              York   
74      M6E              York   
75      M6G  Downtown Toronto   
76      M6H      West Toronto   
77      M6J      West Toronto   
78      M6K      West Toronto   
79      M6L        North York   
80      M6M              York   
81      M6N              York   
82      M6P      West Toronto   
83      M6R      West Toronto   
84      M6S      West Toronto   
85      M7A  Downtown Toronto   
86      M7R       Mississauga   
87      M7Y      East Toronto   
88      M8V         Etobicoke   
89      M8W         Etobicoke   
90      M8X         Etobicoke   
91      M8Y         Etobicoke   
92      M8Z         Etobicoke   
93      M9A      Queen's Park   
94      M9B         Etobicoke   
95      M9C         Etobicoke   
96      M9L        North York   
97      M9M        North York   
98      M9N              York   
99      M9P         Etobicoke   

                                         Neighborhood   Latitude  Longitude  
0                                      Rouge, Malvern  43.806686 -79.194353  
1              Highland Creek, Rouge Hill, Port Union  43.784535 -79.160497  
2                   Guildwood, Morningside, West Hill  43.763573 -79.188711  
3                                              Woburn  43.770992 -79.216917  
4                                           Cedarbrae  43.773136 -79.239476  
5                                 Scarborough Village  43.744734 -79.239476  
6         East Birchmount Park, Ionview, Kennedy Park  43.727929 -79.262029  
7                     Clairlea, Golden Mile, 

In [70]:
# Let's check our neighborhood and borough counts. Should still have 103 postal codes and 11 boroughs.
print('The dataframe has {} postal codes and {} boroughs.'.format(
        len(neighborhoods_df['Postcode'].unique()),
        len(neighborhoods_df['Borough'].unique())
    )
)

The dataframe has 103 postal codes and 11 boroughs.


# 2. Exploring and Clustering the Groups of Toronto

### Neighborhood Map Visualization

We will now analyze and group each neighborhood set based on the types of locations within each area. Areas with similar location data (shopping, cafes, parks, etc.) will be grouped into the same group using k-Means.

Let's start by getting a map of the area.

In [71]:
address = 'Toronto, Canada'

geolocator = Nominatim(user_agent="toronto_explorer")
location = geolocator.geocode(address)
latitude = location.latitude
longitude = location.longitude
print('The geograpical coordinates of Toronto, Canada are {}, {}.'.format(latitude, longitude))

The geograpical coordinates of Toronto, Canada are 43.653963, -79.387207.


I performed this analysis with ONLY boroughs that contain 'Toronto' at first, but then I decided to do a larger analysis for the whole city.

The following commented-out code was needed for the 'Toronto'-only version:

In [72]:
#toronto_df = neighborhoods_df.loc[(neighborhoods_df['Borough'].str.contains('Toronto'))]

#print(toronto_df)

In [73]:
# create map of Toronto using latitude and longitude values
#toronto_map = folium.Map(location=[latitude, longitude], zoom_start=11.5)

## add markers to map
#for lat, lng, borough, neighborhood in zip(toronto_df['Latitude'], toronto_df['Longitude'], toronto_df['Borough'], toronto_df['Neighborhood']):
#    label = '{}, {}'.format(neighborhood, borough)
#    label = folium.Popup(label, parse_html=True)
#    folium.CircleMarker(
#        [lat, lng],
#        radius=5,
#        popup=label,
#        color='blue',
#        fill=True,
#        fill_color='#3186cc',
#        fill_opacity=0.7,
#        parse_html=False).add_to(toronto_map)  
#    
#toronto_map

Analysis re-done with all of Toronto:

In [74]:
# create map of Toronto using latitude and longitude values
toronto_map = folium.Map(location=[latitude, longitude], zoom_start=10.5)

# add markers to map
for lat, lng, borough, neighborhood in zip(neighborhoods_df['Latitude'], neighborhoods_df['Longitude'], neighborhoods_df['Borough'], neighborhoods_df['Neighborhood']):
    label = '{}, {}'.format(neighborhood, borough)
    label = folium.Popup(label, parse_html=True)
    folium.CircleMarker(
        [lat, lng],
        radius=5,
        popup=label,
        color='blue',
        fill=True,
        fill_color='#3186cc',
        fill_opacity=0.7,
        parse_html=False).add_to(toronto_map)  
    
toronto_map

Define Foursquare credentials and version

In [75]:
# The code was removed by Watson Studio for sharing.

Your credentials: [hidden for assignment]


### Fetch venues for analysis

Next, let's create a function to get all the venues within 500m of each neighborhood in Toronto.

In [76]:
def getNearbyVenues(names, latitudes, longitudes, radius=500):
    
    venues_list=[]
    for name, lat, lng in zip(names, latitudes, longitudes):
        print(name)
            
        # create the API request URL
        url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
            CLIENT_ID, 
            CLIENT_SECRET, 
            VERSION, 
            lat, 
            lng, 
            radius, 
            LIMIT)
            
        # make the GET request
        results = requests.get(url).json()["response"]['groups'][0]['items']
        
        # return only relevant information for each nearby venue
        venues_list.append([(
            name, 
            lat, 
            lng, 
            v['venue']['name'], 
            v['venue']['location']['lat'], 
            v['venue']['location']['lng'],  
            v['venue']['categories'][0]['name']) for v in results])

    nearby_venues = pd.DataFrame([item for venue_list in venues_list for item in venue_list])
    nearby_venues.columns = ['Neighborhood', 
                  'Neighborhood Latitude', 
                  'Neighborhood Longitude', 
                  'Venue', 
                  'Venue Latitude', 
                  'Venue Longitude', 
                  'Venue Category']
    
    return(nearby_venues)

In [77]:
# Let's call the function and see what kind of venues we get
toronto_venues = getNearbyVenues(names=neighborhoods_df['Neighborhood'],
                                   latitudes=neighborhoods_df['Latitude'],
                                   longitudes=neighborhoods_df['Longitude']
                                  )

Rouge, Malvern
Highland Creek, Rouge Hill, Port Union
Guildwood, Morningside, West Hill
Woburn
Cedarbrae
Scarborough Village
East Birchmount Park, Ionview, Kennedy Park
Clairlea, Golden Mile, Oakridge
Cliffcrest, Cliffside, Scarborough Village West
Birch Cliff, Cliffside West
Dorset Park, Scarborough Town Centre, Wexford Heights
Maryvale, Wexford
Agincourt
Clarks Corners, Sullivan, Tam O'Shanter
Agincourt North, L'Amoreaux East, Milliken, Steeles East
L'Amoreaux West
Upper Rouge
Hillcrest Village
Fairview, Henry Farm, Oriole
Bayview Village
Silver Hills, York Mills
Newtonbrook, Willowdale
Willowdale South
York Mills West
Willowdale West
Parkwoods
Don Mills North
Flemingdon Park, Don Mills South
Bathurst Manor, Downsview North, Wilson Heights
Northwood Park, York University
CFB Toronto, Downsview East
Downsview West
Downsview Central
Downsview Northwest
Victoria Village
Woodbine Gardens, Parkview Hill
Woodbine Heights
The Beaches
Leaside
Thorncliffe Park
East Toronto
The Danforth West, 

We have now pulled all venues within 500m of each neighborhood. Let's take a look at the venues.

In [78]:
#Check number of venues
print(toronto_venues.shape)
toronto_venues.head()

(2213, 7)


Neighborhood  Neighborhood Latitude  \
0                          Rouge, Malvern              43.806686   
1                          Rouge, Malvern              43.806686   
2  Highland Creek, Rouge Hill, Port Union              43.784535   
3  Highland Creek, Rouge Hill, Port Union              43.784535   
4  Highland Creek, Rouge Hill, Port Union              43.784535   

   Neighborhood Longitude                      Venue  Venue Latitude  \
0              -79.194353                    Wendy's       43.807448   
1              -79.194353      Interprovincial Group       43.805630   
2              -79.160497     Chris Effects Painting       43.784343   
3              -79.160497      Royal Canadian Legion       43.782533   
4              -79.160497  Affordable Toronto Movers       43.787919   

   Venue Longitude              Venue Category  
0       -79.199056        Fast Food Restaurant  
1       -79.200378                  Print Shop  
2       -79.163742  Construction & Landscaping  
3       -79.163085                         Bar  
4       -79.162977               Moving Target

In [79]:
# Let's check how many entries there are for each neighborhood.
toronto_venues.groupby('Neighborhood').count()

Neighborhood Latitude  \
Neighborhood                                                                
Adelaide, King, Richmond                                              100   
Agincourt                                                               5   
Agincourt North, L'Amoreaux East, Milliken, Ste...                      2   
Albion Gardens, Beaumond Heights, Humbergate, J...                     10   
Alderwood, Long Branch                                                  9   
Bathurst Manor, Downsview North, Wilson Heights                        21   
Bayview Village                                                         4   
Bedford Park, Lawrence Manor East                                      25   
Berczy Park                                                            55   
Birch Cliff, Cliffside West                                             4   
Bloordale Gardens, Eringate, Markland Wood, Old...                      9   
Brockton, Exhibition Place, Parkdale Village                           24   
Business Reply Mail Processing Centre 969 Eastern                      17   
CFB Toronto, Downsview East                                             4   
CN Tower, Bathurst Quay, Island airport, Harbou...                     16   
Cabbagetown, St. James Town                                            42   
Caledonia-Fairbanks                                                     5   
Canada Post Gateway Processing Centre                                  12   
Cedarbrae                                                               8   
Central Bay Street                                                     84   
Chinatown, Grange Park, Kensington Market                              80   
Christie                                                               18   
Church and Wellesley                                                   81   
Clairlea, Golden Mile, Oakridge                                         9   
Clarks Corners, Sullivan, Tam O'Shanter                                13   
Cliffcrest, Cliffside, Scarborough Village West                         2   
Cloverdale, Islington, Martin Grove, Princess G...                      1   
Commerce Court, Victoria Hotel                                        100   
Davisville                                                             35   
Davisville North                                                        7   
Deer Park, Forest Hill SE, Rathnelly, South Hil...                     14   
Del Ray, Keelesdale, Mount Dennis, Silverthorn                          4   
Design Exchange, Toronto Dominion Centre                              100   
Don Mills North                                                         5   
Dorset Park, Scarborough Town Centre, Wexford H...                      5   
Dovercourt Village, Dufferin                                           19   
Downsview Central                                                       3   
Downsview Northwest                                                     4   
Downsview West                                                          4   
Downsview, North Park, Upwood Park                                      4   
East Birchmount Park, Ionview, Kennedy Park                             4   
East Toronto                                                            3   
Emery, Humberlea                                                        2   
Fairview, Henry Farm, Oriole                                           63   
First Canadian Place, Underground city                                100   
Flemingdon Park, Don Mills South                                       21   
Forest Hill North, Forest Hill West                                     4   
Glencairn                                                               4   
Guildwood, Morningside, West Hill                                       7   
Harbord, University of Toronto                                         36   
Harbourfront                                    

In [80]:
# Check the number of UNIQUE categories
print('There are {} unique categories.'.format(len(toronto_venues['Venue Category'].unique())))

There are 266 unique categories.


### Mathematical Analysis - One hot encoding and grouping

One Hot Encoding - Converting categorical variables into a numerical form for mathematical analysis.

In [81]:
# One hot encoding
toronto_onehot = pd.get_dummies(toronto_venues[['Venue Category']], prefix="", prefix_sep="")

# add neighborhood column back to dataframe
toronto_onehot['Neighborhood'] = toronto_venues['Neighborhood']

# Let's look at all the different columns
cols = list(toronto_onehot)
#print(cols)

# Move the neighborhood column to the front of the list
cols.insert(0, cols.pop(cols.index('Neighborhood')))
#print(cols)

# Re-order the toronto_onehot df according to the re-ordered columns list
toronto_onehot = toronto_onehot.loc[toronto_onehot.index[:], cols]
toronto_onehot.head()

Neighborhood  Accessories Store  \
0                          Rouge, Malvern                  0   
1                          Rouge, Malvern                  0   
2  Highland Creek, Rouge Hill, Port Union                  0   
3  Highland Creek, Rouge Hill, Port Union                  0   
4  Highland Creek, Rouge Hill, Port Union                  0   

   Afghan Restaurant  Airport  Airport Food Court  Airport Gate  \
0                  0        0                   0             0   
1                  0        0                   0             0   
2                  0        0                   0             0   
3                  0        0                   0             0   
4                  0        0                   0             0   

   Airport Lounge  Airport Service  Airport Terminal  American Restaurant  \
0               0                0                 0                    0   
1               0                0                 0                    0   
2               0                0                 0                    0   
3               0                0                 0                    0   
4               0                0                 0                    0   

   Antique Shop  Aquarium  Art Gallery  Arts & Crafts Store  Asian Restaurant  \
0             0         0            0                    0                 0   
1             0         0            0                    0                 0   
2             0         0            0                    0                 0   
3             0         0            0                    0                 0   
4             0         0            0                    0                 0   

   Athletics & Sports  Auto Workshop  BBQ Joint  Baby Store  Bagel Shop  \
0                   0              0          0           0           0   
1                   0              0          0           0           0   
2                   0              0          0           0           0   
3                   0              0          0           0           0   
4                   0              0          0           0           0   

   Bakery  Bank  Bar  Baseball Field  Baseball Stadium  Basketball Court  \
0       0     0    0               0                 0                 0   
1       0     0    0               0                 0                 0   
2       0     0    0               0                 0                 0   
3       0     0    1               0                 0                 0   
4       0     0    0               0                 0                 0   

   Basketball Stadium  Beach  Bed & Breakfast  Beer Bar  Beer Store  \
0                   0      0                0         0           0   
1                   0      0                0         0           0   
2                   0      0                0         0           0   
3                   0      0                0         0           0   
4                   0      0                0         0           0   

   Belgian Restaurant  Bike Shop  Bistro  Board Shop  Boat or Ferry  \
0                   0          0       0           0              0   
1                   0          0       0           0              0   
2                   0          0       0           0              0   
3                   0          0       0           0              0   
4                   0          0       0           0              0   

   Bookstore  Boutique  Brazilian Restaurant  Breakfast Spot  Brewery  \
0          0         0                     0               0        0   
1          0         0                     0               0        0   
2          0         0                     0               0        0   
3          0         0                     0               0        0   
4          0         0                     0               0        0   

   Bridal Shop  Bubble Tea Shop  Building  Burger Joint  Burrito Place  \
0            0  

In [82]:
# Let's confirm that we still have all the entries. (2213 entries with 266 categories)
toronto_onehot.shape

(2213, 266)

Let's group rows by neighborhood and take the mean of the frequency of occurance for each category

In [83]:
toronto_grouped = toronto_onehot.groupby('Neighborhood').mean().reset_index()
toronto_grouped

Neighborhood  Accessories Store  \
0                             Adelaide, King, Richmond           0.000000   
1                                            Agincourt           0.000000   
2    Agincourt North, L'Amoreaux East, Milliken, St...           0.000000   
3    Albion Gardens, Beaumond Heights, Humbergate, ...           0.000000   
4                               Alderwood, Long Branch           0.000000   
5      Bathurst Manor, Downsview North, Wilson Heights           0.000000   
6                                      Bayview Village           0.000000   
7                    Bedford Park, Lawrence Manor East           0.000000   
8                                          Berczy Park           0.000000   
9                          Birch Cliff, Cliffside West           0.000000   
10   Bloordale Gardens, Eringate, Markland Wood, Ol...           0.000000   
11        Brockton, Exhibition Place, Parkdale Village           0.000000   
12   Business Reply Mail Processing Centre 969 Eastern           0.000000   
13                         CFB Toronto, Downsview East           0.000000   
14   CN Tower, Bathurst Quay, Island airport, Harbo...           0.000000   
15                         Cabbagetown, St. James Town           0.000000   
16                                 Caledonia-Fairbanks           0.000000   
17               Canada Post Gateway Processing Centre           0.000000   
18                                           Cedarbrae           0.000000   
19                                  Central Bay Street           0.000000   
20           Chinatown, Grange Park, Kensington Market           0.000000   
21                                            Christie           0.000000   
22                                Church and Wellesley           0.000000   
23                     Clairlea, Golden Mile, Oakridge           0.000000   
24             Clarks Corners, Sullivan, Tam O'Shanter           0.000000   
25     Cliffcrest, Cliffside, Scarborough Village West           0.000000   
26   Cloverdale, Islington, Martin Grove, Princess ...           0.000000   
27                      Commerce Court, Victoria Hotel           0.000000   
28                                          Davisville           0.000000   
29                                    Davisville North           0.000000   
30   Deer Park, Forest Hill SE, Rathnelly, South Hi...           0.000000   
31      Del Ray, Keelesdale, Mount Dennis, Silverthorn           0.000000   
32            Design Exchange, Toronto Dominion Centre           0.000000   
33                                     Don Mills North           0.000000   
34   Dorset Park, Scarborough Town Centre, Wexford ...           0.000000   
35                        Dovercourt Village, Dufferin           0.000000   
36                                   Downsview Central           0.000000   
37                                 Downsview Northwest           0.000000   
38                                      Downsview West           0.000000   
39                  Downsview, North Park, Upwood Park           0.000000   
40         East Birchmount Park, Ionview, Kennedy Park           0.000000   
41                                        East Toronto           0.000000   
42                                    Emery, Humberlea           0.000000   
43                        Fairview, Henry Farm, Oriole           0.000000   
44              First Canadian Place, Underground city           0.000000   
45                    Flemingdon Park, Don Mills South           0.000000   
46                 Forest Hill North, Forest Hill West           0.000000   
47                                           Glencairn           0.000000   
48                   Guildwood, Morningside, West Hill           0.000000   
49                      Harbord, University of Toronto           0.000000   
50                                        Harbourfront           0.000000   
51   Harbourfront East, Toronto Island

In [84]:
# Now we've grouped the same neighborhoods together.
toronto_grouped.shape

(101, 266)

 Note: from the 103 postal codes, 2 seem to have had no registered venues, we now only have 101 neighborhood sets.

Print each neighborhood along with the top 5 most common venues

In [85]:
num_top_venues = 5

for hood in toronto_grouped['Neighborhood']:
    print("----"+hood+"----")
    temp = toronto_grouped[toronto_grouped['Neighborhood'] == hood].T.reset_index()
    temp.columns = ['Venue','Freq'] # Name the columns 
    temp = temp.iloc[1:] # Drop the top row
    temp['Freq'] = temp['Freq'].astype(float) #Convert frequency values to float
    temp = temp.round({'Freq': 2}) # And round
    print(temp.sort_values('Freq', ascending=False).reset_index(drop=True).head(num_top_venues))
    print('\n')

----Adelaide, King, Richmond----
          Venue  Freq
0   Coffee Shop  0.07
1    Steakhouse  0.04
2          Café  0.04
3           Bar  0.04
4  Burger Joint  0.03


----Agincourt----
                       Venue  Freq
0                     Lounge   0.2
1             Breakfast Spot   0.2
2  Latin American Restaurant   0.2
3             Clothing Store   0.2
4               Skating Rink   0.2


----Agincourt North, L'Amoreaux East, Milliken, Steeles East----
               Venue  Freq
0         Playground   0.5
1               Park   0.5
2  Accessories Store   0.0
3        Men's Store   0.0
4  Mobile Phone Shop   0.0


----Albion Gardens, Beaumond Heights, Humbergate, Jamestown, Mount Olive, Silverstone, South Steeles, Thistletown----
                 Venue  Freq
0        Grocery Store   0.2
1          Pizza Place   0.1
2  Fried Chicken Joint   0.1
3          Coffee Shop   0.1
4       Sandwich Place   0.1


----Alderwood, Long Branch----
          Venue  Freq
0   Pizza Place  0.22
1    

### Getting the top venues in each neighborhood

In [86]:
# Let's create a function to get the most common venue types in each neighborhood
def return_most_common_venues(row, num_top_venues):
    row_categories = row.iloc[1:]
    row_categories_sorted = row_categories.sort_values(ascending=False)
    
    return row_categories_sorted.index.values[0:num_top_venues]

In [87]:
num_top_venues = 10

indicators = ['st', 'nd', 'rd']

# create columns according to number of top venues
columns = ['Neighborhood']
for ind in np.arange(num_top_venues):
    try:
        columns.append('{}{} Most Common Venue'.format(ind+1, indicators[ind]))
    except:
        columns.append('{}th Most Common Venue'.format(ind+1))

# create a new dataframe
neighborhoods_venues_sorted = pd.DataFrame(columns=columns)
neighborhoods_venues_sorted['Neighborhood'] = toronto_grouped['Neighborhood']

for ind in np.arange(toronto_grouped.shape[0]):
    neighborhoods_venues_sorted.iloc[ind, 1:] = return_most_common_venues(toronto_grouped.iloc[ind, :], num_top_venues)

neighborhoods_venues_sorted.head()

Neighborhood  \
0                           Adelaide, King, Richmond   
1                                          Agincourt   
2  Agincourt North, L'Amoreaux East, Milliken, St...   
3  Albion Gardens, Beaumond Heights, Humbergate, ...   
4                             Alderwood, Long Branch   

       1st Most Common Venue 2nd Most Common Venue 3rd Most Common Venue  \
0                Coffee Shop            Steakhouse                  Café   
1  Latin American Restaurant          Skating Rink                Lounge   
2                       Park            Playground      Doner Restaurant   
3              Grocery Store           Pizza Place          Liquor Store   
4                Pizza Place        Sandwich Place           Coffee Shop   

  4th Most Common Venue 5th Most Common Venue 6th Most Common Venue  \
0                   Bar       Thai Restaurant        Breakfast Spot   
1        Clothing Store        Breakfast Spot             Drugstore   
2      Department Store          Dessert Shop    Dim Sum Restaurant   
3  Fast Food Restaurant            Beer Store        Sandwich Place   
4                   Gym          Skating Rink                   Pub   

  7th Most Common Venue 8th Most Common Venue 9th Most Common Venue  \
0          Burger Joint                Bakery        Cosmetics Shop   
1        Discount Store               Dog Run      Doner Restaurant   
2                 Diner        Discount Store               Dog Run   
3   Fried Chicken Joint           Coffee Shop              Pharmacy   
4              Pharmacy                  Pool           Yoga Studio   

  10th Most Common Venue  
0       Asian Restaurant  
1             Donut Shop  
2             Donut Shop  
3             Comic Shop  
4           Dessert Shop

We now have the 10 most common venue types in each neighborhood set. Now to group them with K-Means

# 3. Clustering the Neighborhoods with K-Means

### K-Means Clustering

In [88]:
# set number of clusters
kclusters = 5

toronto_grouped_clustering = toronto_grouped.drop('Neighborhood', axis=1)

# run k-means clustering
kmeans = KMeans(n_clusters=kclusters, random_state=0).fit(toronto_grouped_clustering)

# check cluster labels generated for each row in the dataframe
kmeans.labels_[0:] 

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 1, 3, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 2, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1], dtype=int32)

Interestingly, it seems as if with 5 clusters as in the New York analysis, most neighborhoods fall into one category. 

Let's create new dataframe that includes cluster labels as well as top 10 venues for each neighborhood.

In [89]:
# add clustering labels
neighborhoods_venues_sorted.insert(0, 'Cluster Labels', kmeans.labels_)

toronto_merged = neighborhoods_df

# merge toronto_grouped with toronto_data to add latitude/longitude for each neighborhood
toronto_merged = toronto_merged.join(neighborhoods_venues_sorted.set_index('Neighborhood'), on='Neighborhood', how='right')

toronto_merged.head() # check the last columns!

Postcode      Borough                            Neighborhood   Latitude  \
0      M1B  Scarborough                          Rouge, Malvern  43.806686   
1      M1C  Scarborough  Highland Creek, Rouge Hill, Port Union  43.784535   
2      M1E  Scarborough       Guildwood, Morningside, West Hill  43.763573   
3      M1G  Scarborough                                  Woburn  43.770992   
4      M1H  Scarborough                               Cedarbrae  43.773136   

   Longitude  Cluster Labels 1st Most Common Venue  \
0 -79.194353               0  Fast Food Restaurant   
1 -79.160497               0                   Bar   
2 -79.188711               0     Electronics Store   
3 -79.216917               0           Coffee Shop   
4 -79.239476               0                Bakery   

        2nd Most Common Venue 3rd Most Common Venue 4th Most Common Venue  \
0                  Print Shop           Yoga Studio            Donut Shop   
1  Construction & Landscaping         Moving Target           Yoga Studio   
2              Breakfast Spot           Pizza Place    Mexican Restaurant   
3           Korean Restaurant           Yoga Studio             Drugstore   
4                 Gas Station   Fried Chicken Joint      Hakka Restaurant   

  5th Most Common Venue 6th Most Common Venue 7th Most Common Venue  \
0    Dim Sum Restaurant                 Diner        Discount Store   
1            Donut Shop                 Diner        Discount Store   
2   Rental Car Location          Intersection        Medical Center   
3                 Diner        Discount Store               Dog Run   
4  Caribbean Restaurant    Athletics & Sports       Thai Restaurant   

  8th Most Common Venue 9th Most Common Venue       10th Most Common Venue  
0               Dog Run      Doner Restaurant                    Drugstore  
1               Dog Run      Doner Restaurant                    Drugstore  
2           Yoga Studio               Dog Run           Dim Sum Restaurant  
3      Doner Restaurant            Donut Shop  Eastern European Restaurant  
4                  Bank          Dessert Shop           Dim Sum Restaurant

### Map visualization of K-Means clustered Toronto

In [90]:
# create map
map_clusters = folium.Map(location=[latitude, longitude], zoom_start=11)

# set color scheme for the clusters
x = np.arange(kclusters)
ys = [i + x + (i*x)**2 for i in range(kclusters)]
colors_array = cm.rainbow(np.linspace(0, 1, len(ys)))
rainbow = [colors.rgb2hex(i) for i in colors_array]

# add markers to the map
markers_colors = []
for lat, lon, poi, cluster in zip(toronto_merged['Latitude'], toronto_merged['Longitude'], toronto_merged['Neighborhood'], toronto_merged['Cluster Labels']):
    label = folium.Popup(str(poi) + ' Cluster ' + str(cluster), parse_html=True)
    folium.CircleMarker(
        [lat, lon],
        radius=5,
        popup=label,
        color=rainbow[cluster-1],
        fill=True,
        fill_color=rainbow[cluster-1],
        fill_opacity=0.7).add_to(map_clusters)
       
map_clusters

We can see that most neighborhoods in Toronto are similar (the "red dot" category). Let's examine what each color could possibly mean.

### Examine Clusters

### Cluster 1 (Red)

In [91]:
toronto_merged.loc[toronto_merged['Cluster Labels'] == 0, toronto_merged.columns[[1] + list(range(5, toronto_merged.shape[1]))]]

Borough  Cluster Labels      1st Most Common Venue  \
0         Scarborough               0       Fast Food Restaurant   
1         Scarborough               0                        Bar   
2         Scarborough               0          Electronics Store   
3         Scarborough               0                Coffee Shop   
4         Scarborough               0                     Bakery   
6         Scarborough               0           Department Store   
7         Scarborough               0                     Bakery   
8         Scarborough               0        American Restaurant   
9         Scarborough               0            College Stadium   
10        Scarborough               0          Indian Restaurant   
11        Scarborough               0  Middle Eastern Restaurant   
12        Scarborough               0  Latin American Restaurant   
13        Scarborough               0                Pizza Place   
15        Scarborough               0         Chinese Restaurant   
18         North York               0             Clothing Store   
19         North York               0                       Café   
20         North York               0                  Cafeteria   
22         North York               0           Ramen Restaurant   
24         North York               0                    Butcher   
26         North York               0       Gym / Fitness Center   
27         North York               0                        Gym   
28         North York               0                Coffee Shop   
29         North York               0                        Bar   
30         North York               0                Snack Place   
31         North York               0                       Park   
33         North York               0       Gym / Fitness Center   
34         North York               0      Portuguese Restaurant   
35          East York               0                Pizza Place   
36          East York               0                Curling Ice   
37       East Toronto               0                      Trail   
38          East York               0        Sporting Goods Shop   
39          East York               0          Indian Restaurant   
41       East Toronto               0           Greek Restaurant   
42       East Toronto               0                       Park   
43       East Toronto               0                       Café   
44    Central Toronto               0                       Lake   
45    Central Toronto               0                        Gym   
46    Central Toronto               0             Clothing Store   
47    Central Toronto               0             Sandwich Place   
49    Central Toronto               0                        Pub   
51   Downtown Toronto               0                Coffee Shop   
52   Downtown Toronto               0                Coffee Shop   
53   Downtown Toronto               0                Coffee Shop   
54   Downtown Toronto               0                Coffee Shop   
55   Downtown Toronto               0                Coffee Shop   
56   Downtown Toronto               0                Coffee Shop   
57   Downtown Toronto               0                Coffee Shop   
58   Downtown Toronto               0                Coffee Shop   
59   Downtown Toronto               0                Coffee Shop   
60   Downtown Toronto               0                Coffee Shop   
61   Downtown Toronto               0                Coffee Shop   
62         North York               0             Sandwich Place   
63    Central Toronto               0                     Garden   
64    Central Toronto               0                      Trail   
65    Central Toronto               0                       Café   
66   Downtown Toronto               0                       Café   
67   Downtown Toronto               0                        Bar   
68   Downtown Toronto               0            Airport Service   
69

Looking at the most common venues in the red cluster 1, we can see there are mainly places to eat, with some other places commonly visited in everyday life. Drugstores, coffee shops, and gas stations are all places we frequent in daily life. From this, we can assume that the red neighborhoods are most likely places where people live.

### Cluster 2 (Purple)

In [92]:
toronto_merged.loc[toronto_merged['Cluster Labels'] == 1, toronto_merged.columns[[1] + list(range(5, toronto_merged.shape[1]))]]

Borough  Cluster Labels 1st Most Common Venue  \
5        Scarborough               1            Playground   
14       Scarborough               1                  Park   
23        North York               1                  Park   
25        North York               1                  Park   
40         East York               1                  Park   
48   Central Toronto               1                  Park   
50  Downtown Toronto               1                  Park   
74              York               1                  Park   
90         Etobicoke               1                  Park   
98              York               1                  Park   

   2nd Most Common Venue 3rd Most Common Venue 4th Most Common Venue  \
5            Yoga Studio            Donut Shop          Dessert Shop   
14            Playground      Doner Restaurant      Department Store   
23                  Bank     Convenience Store  Ethiopian Restaurant   
25     Food & Drink Shop      Department Store  Ethiopian Restaurant   
40     Convenience Store           Coffee Shop    Dim Sum Restaurant   
48            Playground          Tennis Court            Restaurant   
50                 Trail            Playground          Dessert Shop   
74         Women's Store  Fast Food Restaurant                Market   
90                 River         Deli / Bodega   Empanada Restaurant   
98     Convenience Store           Event Space  Ethiopian Restaurant   

   5th Most Common Venue        6th Most Common Venue  \
5     Dim Sum Restaurant                        Diner   
14          Dessert Shop           Dim Sum Restaurant   
23   Empanada Restaurant            Electronics Store   
25   Empanada Restaurant            Electronics Store   
40                 Diner               Discount Store   
48   Dumpling Restaurant                    Drugstore   
50    Dim Sum Restaurant                        Diner   
74            Donut Shop           Dim Sum Restaurant   
90     Electronics Store  Eastern European Restaurant   
98   Empanada Restaurant            Electronics Store   

          7th Most Common Venue 8th Most Common Venue 9th Most Common Venue  \
5                Discount Store               Dog Run      Doner Restaurant   
14                        Diner        Discount Store               Dog Run   
23  Eastern European Restaurant   Dumpling Restaurant          Dessert Shop   
25  Eastern European Restaurant   Dumpling Restaurant             Drugstore   
40                      Dog Run      Doner Restaurant            Donut Shop   
48  Eastern European Restaurant            Donut Shop      Doner Restaurant   
50               Discount Store               Dog Run      Doner Restaurant   
74                        Diner        Discount Store               Dog Run   
90          Dumpling Restaurant             Drugstore            Donut Shop   
98  Eastern European Restaurant   Dumpling Restaurant      Department Store   

   10th Most Common Venue  
5               Drugstore  
14             Donut Shop  
23              Drugstore  
25             Donut Shop  
40              Drugstore  
48           Dance Studio  
50             Donut Shop  
74       Doner Restaurant  
90       Doner Restaurant  
98              Drugstore

For the purple cluster, we can the most common venue is parks. Parks are then followed by places like tennis courts/dance studios, event spaces, convenience stores, and fast food/snack/dessert shops. From this, we can gather that these are more recreational spaces. Places where people congregate for exercise and socializing.

### Cluster 3 (Light Blue)

In [93]:
toronto_merged.loc[toronto_merged['Cluster Labels'] == 2, toronto_merged.columns[[1] + list(range(5, toronto_merged.shape[1]))]]

Borough  Cluster Labels 1st Most Common Venue 2nd Most Common Venue  \
21  North York               2                   Gym            Donut Shop   

   3rd Most Common Venue 4th Most Common Venue 5th Most Common Venue  \
21          Dessert Shop    Dim Sum Restaurant                 Diner   

   6th Most Common Venue 7th Most Common Venue 8th Most Common Venue  \
21        Discount Store               Dog Run      Doner Restaurant   

   9th Most Common Venue 10th Most Common Venue  
21           Yoga Studio       Department Store

This cluster seemed to be significantly different from the rest just because of the existance of a gym. It was most likely similar to one of the other neighborhoods, but as a result of our request of 5 clusters, needed to find something different enough to warrant a separate category. The algorithm seems to have used 'Gym' for this.

### Cluster 4 (Light Green)

In [94]:
toronto_merged.loc[toronto_merged['Cluster Labels'] == 3, toronto_merged.columns[[1] + list(range(5, toronto_merged.shape[1]))]]

Borough  Cluster Labels       1st Most Common Venue  \
32  North York               3              Baseball Field   
91   Etobicoke               3                Home Service   
97  North York               3  Construction & Landscaping   

   2nd Most Common Venue 3rd Most Common Venue 4th Most Common Venue  \
32          Home Service            Food Truck           Yoga Studio   
91        Baseball Field           Yoga Studio            Donut Shop   
97        Baseball Field           Yoga Studio             Drugstore   

   5th Most Common Venue 6th Most Common Venue 7th Most Common Venue  \
32          Dessert Shop                 Diner        Discount Store   
91                 Diner        Discount Store               Dog Run   
97                 Diner        Discount Store               Dog Run   

   8th Most Common Venue 9th Most Common Venue 10th Most Common Venue  
32               Dog Run      Doner Restaurant             Donut Shop  
91      Doner Restaurant             Drugstore           Dessert Shop  
97      Doner Restaurant            Donut Shop    Dumpling Restaurant

This was most likely another result of our choice of 5 clusters. This cluster seems to have been differentiated based on it's existance of home repair/construction shops. All 3 boroughs have home repair/construction in the 1st and 2nd most common venue, so was likely separated based on those.

### Cluster 5 (Orange)

In [95]:
toronto_merged.loc[toronto_merged['Cluster Labels'] == 4, toronto_merged.columns[[1] + list(range(5, toronto_merged.shape[1]))]]

Borough  Cluster Labels     1st Most Common Venue  \
17  North York               4  Mediterranean Restaurant   
94   Etobicoke               4               Golf Course   

   2nd Most Common Venue 3rd Most Common Venue 4th Most Common Venue  \
17           Golf Course               Dog Run                  Pool   
94           Yoga Studio            Donut Shop          Dessert Shop   

   5th Most Common Venue 6th Most Common Venue 7th Most Common Venue  \
17           Yoga Studio          Dessert Shop    Dim Sum Restaurant   
94    Dim Sum Restaurant                 Diner        Discount Store   

   8th Most Common Venue 9th Most Common Venue 10th Most Common Venue  
17                 Diner        Discount Store       Doner Restaurant  
94               Dog Run      Doner Restaurant              Drugstore

Cluster 5 seems to have been separated due to the existance of the golf courses, which only existed in these areas, meriting these 2 neighborhoods being clustered separately. We can see there were also pools and dog runs in the area. These areas are most likely good exercising/socializing places similar to purple.

## 4. Summary and Conclusion

### Summary

The purpose of this analysis was to group and cluster each neighborhood of Toronto into similar neighborhoods based on the venues that exist within them. Neighborhoods with similar venues were grouped together into a total of 5 clusters:

Cluster 1 (Red): Easy living - Restaurants, convenience stores and drug stores, cafes, gas stations, and bars. Places where people live.
Cluster 2 (Purple): Socializing and outdoors - Parks, tennis courts, event spaces, and cafes/donut shops. Places where people go for socializing and exercise.
Cluster 3 (Light Blue): Gym! - With only 4 clusters, this most likely would have been purple.
Cluster 4 (Light Green): Home Care -  Construction, things for home repair and maintenance, and shops seem to be the theme.
Cluster 5 (Orange): Exercise and Socializing - Similar to purple, these areas contained golf courses, swimming pools, and dog runs. Good for exercise! 

### K-Means

In our K-Means analysis I chose to use 5 clusters, as was done in the analysis of New York City. Because of the overwhelming number of neighborhoods placed into the same cluster (red), we probably could have used more clusters for a more accurate and deeper analysis. Splitting up those red clusters further might have gotten more varied results with more distinctive neighborhoods.

### Closing Remarks

I learned more on this one project than I did in all the other labs put together. Having to actually do something for yourself, rather than just run cells that are mostly completed forced me to spend most of my time just learning what exactly each line of code does and how to use it. The analysis performed could probably have been done cleaner and more efficiently, and I think there is still some refinement that could be done with the number of clusters, but overall I am happy with the result, which seemed reasonable. 

Thank you to the professor and staff for the great course and to you, the reader, for reading my project report!